### ISSUE TITLE
Exception when exporting build definition VS2015

### ISSUE THREAD

**Issue by srikcgaa2** [tfsbuildextensions/BuildManager#28]
I was using this plugin without any issues when we had VS2013.  Recently we upgraded to VS2015 and I installed the latest version 2.14.023 version where I am able to see all the build definitions but when I export, I get the following exception.  We connect to TFS 2012 build server

System.Xaml.XamlObjectWriterException: The invocation of the constructor on type 'Microsoft.TeamFoundation.Build.Workflow.Activities.AgentSettings' that matches the specified binding constraints threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.TeamFoundation.Build.Common, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

   at Microsoft.TeamFoundation.Build.Workflow.Activities.AgentSettings..ctor()

   --- End of inner exception stack trace ---

   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)

   at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)

   at System.Xaml.XamlObjectWriter.WriteStartMember(XamlMember property)

   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)

   at System.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)

   at System.Xaml.XamlServices.Load(XamlReader xamlReader)

   at System.Xaml.XamlServices.Load(XmlReader xmlReader)

   at Microsoft.TeamFoundation.Build.Workflow.WorkflowHelpers.DeserializeProcessParameters(String parameterValues)

   at TfsBuildManager.Views.BuildManagerViewModel.ExportDefinition(BuildDefinitionViewModel b, String filePath)

   at TfsBuildManager.Views.BuildManagerViewModel.OnExportBuildDefinition()

**Comment by chijos** [comment]
I can see the same issue when I try to clone a build to another branch. I am using VS 2015 with the 2.14.0.23 version. FWIW, this seems to work fine if you have VS 2013 installed alongside.

**Comment by srikcgaa2** [comment]
Yes, I had uninstalled VS2013 after upgrading to VS2015 due to low diskspace issues.  But if I installed VS2013 along with VS2015 it does export even from VS2015.

**Comment by srikcgaa2** [comment]
Clicked the wrong button where I closed by mistake

**Comment by wreynoldson** [comment]
+1, I get this as well, was working recently.

VS 2015 installed only. Will install VS 2013 as a workaround

**Comment by yourbuddypal** [comment]
Same issue for me.  I don't really have the HDD space to spare for an additional VS2013 install.  I had to use a different machine that had the 2012 extension installed to clone my build.

**Comment by geeeyetee** [comment]
A lighter-weight workaround is to install [Team Explorer for Microsoft Visual Studio 2013](https://www.microsoft.com/en-in/download/details.aspx?id=40776). This corrected the error after I launched and then closed the newly-installed Visual Studio 2013 (Shell) and then relaunched Visual Studio 2015.

**Comment by srikcgaa2** [comment]
The suggestion about Team Explorer for 2013 worked for me too.  Thanks!

**Comment by mikefourie** [comment]
2.14.0.24 resolves this. Apologies for the delay.
